# This workflow that is build with html5, css, and javascript.

name: Talk with Sassy

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  build:
   
   runs-on: ubuntu-latest
   
   steps:
   - name: Checkout repository
     uses: actions/checkout@v3
